"""Add resolved flag

Revision ID: 167d7d2c1277
Revises: f2603f00da1f
Create Date: 2024-07-13 12:18:25.782558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167d7d2c1277'
down_revision: Union[str, None] = 'f2603f00da1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('resolved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'resolved')
    # ### end Alembic commands ###
