"""Add dispution description

Revision ID: 4ca8842af3d8
Revises: c12206259610
Create Date: 2024-07-14 02:04:19.420094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca8842af3d8'
down_revision: Union[str, None] = 'c12206259610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disputes', sa.Column('description_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disputes', 'description_hash')
    # ### end Alembic commands ###
