"""Add submission and verification tables

Revision ID: 52e751f3e657
Revises: c606a956a9c7
Create Date: 2024-07-13 00:51:43.144400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e751f3e657'
down_revision: Union[str, None] = 'c606a956a9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('photo_hash', sa.String(), nullable=True),
    sa.Column('description_hash', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_table('verification_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=True),
    sa.Column('verifier_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_requests_id'), 'verification_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_requests_id'), table_name='verification_requests')
    op.drop_table('verification_requests')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
