"""Init

Revision ID: 5ade8e7f9a37
Revises: 
Create Date: 2024-07-12 19:55:22.889146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ade8e7f9a37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('descriptions',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_descriptions_hash'), 'descriptions', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_descriptions_hash'), table_name='descriptions')
    op.drop_table('descriptions')
    # ### end Alembic commands ###
