"""Add Stash Campaign table

Revision ID: c606a956a9c7
Revises: dd7aa459598b
Create Date: 2024-07-12 23:18:43.114811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c606a956a9c7'
down_revision: Union[str, None] = 'dd7aa459598b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stash_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('description_hash', sa.String(), nullable=True),
    sa.Column('campaign_creator', sa.String(), nullable=True),
    sa.Column('reward', sa.Integer(), nullable=True),
    sa.Column('reward_token', sa.String(), nullable=True),
    sa.Column('blockchain', sa.String(), nullable=True),
    sa.Column('token_symbol', sa.String(), nullable=True),
    sa.Column('campaign_type', sa.Integer(), nullable=True),
    sa.Column('max_submissions', sa.Integer(), nullable=True),
    sa.Column('remained_submissions', sa.Integer(), nullable=True),
    sa.Column('top_left_lat', sa.Float(), nullable=True),
    sa.Column('top_left_long', sa.Float(), nullable=True),
    sa.Column('bottom_right_lat', sa.Float(), nullable=True),
    sa.Column('bottom_right_long', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stash_campaigns_id'), 'stash_campaigns', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stash_campaigns_id'), table_name='stash_campaigns')
    op.drop_table('stash_campaigns')
    # ### end Alembic commands ###
