"""Add photos table

Revision ID: dd7aa459598b
Revises: 5ade8e7f9a37
Create Date: 2024-07-12 21:00:18.306625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7aa459598b'
down_revision: Union[str, None] = '5ade8e7f9a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_photos_hash'), 'photos', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_hash'), table_name='photos')
    op.drop_table('photos')
    # ### end Alembic commands ###
